# Generated by Django 6.0.7 on 2026-07-14 21:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='area',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='district',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='division',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='tehsil',
            options={'ordering': ['name']},
        ),
    ]
