# Generated by Django 6.0.7 on 2026-07-14 21:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('complaints', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('worker_remarks', models.TextField(blank=True)),
                ('complaint', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='assignment', to='complaints.complaint')),
                ('manager', models.ForeignKey(blank=True, limit_choices_to={'role': 'manager'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='manager_assignments', to=settings.AUTH_USER_MODEL)),
                ('worker', models.ForeignKey(blank=True, limit_choices_to={'role': 'worker'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='worker_assignments', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
