# Generated by Django 6.0.7 on 2026-07-14 21:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='assignment',
            options={'ordering': ['-assigned_at']},
        ),
    ]
